apiVersion: v1
kind: Pod
metadata:
  name: logstash
  namespace: hackathon
  labels:
    hack: logstash
spec:
  containers:
  - name: logstash
    image: logstash:7.4.0
    command:
      - bin/logstash
      - -f
      - /setup/logstash/logstash.conf
    volumeMounts:
    - name: logstash-config
      mountPath: /setup/logstash
  volumes:
  - name: logstash-config
    configMap:
      name: logstash-config
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: hackathon
  labels:
    hack: logstash
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5044
  selector:
    hack: logstash
