apiVersion: v1
kind: Pod
metadata:
  name: service-b
  namespace: hackathon
  labels:
    hack: service-b
spec:
  containers:
  - name: serviceb
    image: sebosp/playground:b-0.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: hackathon
  labels:
    hack: service-b
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    hack: service-b
